# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    # jbpm api configuration 
    api: 'http://localhost:8080/jbpm-console/rest/'
    username: 'admin'
    password: 'admin'

services:
    jbpm_rest_client:
       class:  Splendornet\JbpmBundle\Service\JbpmRestClient
       arguments: ['%api%','%username%','%password%']
    jbpm_task:
       class:  Splendornet\JbpmBundle\Service\Task
       arguments: ['@jbpm_rest_client']
